steps:
  # Step 1: Install dependencies and run tests + lint
  - name: 'python:3.12.8-slim-bookworm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements-dev.txt
        ruff check src/ tests/
        mypy src/ --ignore-missing-imports
        python -m pytest tests/ -v --tb=short -x \
          --ignore=tests/test_eval.py \
          --cov=src --cov-fail-under=90

  # Step 2: Build Docker image (Artifact Registry, not deprecated gcr.io)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/hey-seven/hey-seven:$COMMIT_SHA', '.']

  # Step 3: Trivy container vulnerability scan (pinned version for reproducible builds)
  - name: 'aquasec/trivy:0.58.2'
    args:
      - 'image'
      - '--severity=CRITICAL,HIGH'
      - '--exit-code=1'
      - '--ignore-unfixed'
      - '--no-progress'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/hey-seven/hey-seven:$COMMIT_SHA'

  # Step 4: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/hey-seven/hey-seven:$COMMIT_SHA']

  # Step 5: Capture current revision for rollback
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run revisions list --service=hey-seven --region=us-central1 \
          --format='value(REVISION)' --limit=1 > /workspace/previous-revision.txt 2>/dev/null || echo "none" > /workspace/previous-revision.txt
        echo "Previous revision: $(cat /workspace/previous-revision.txt)"

  # Step 6: Deploy to Cloud Run with --no-traffic (canary-safe)
  # --allow-unauthenticated is defense-in-depth: Cloud Run allows public access,
  # while the app layer enforces API key auth via ApiKeyMiddleware + hmac.compare_digest.
  # This avoids requiring IAM tokens for the demo while maintaining app-level access
  # control. Webhooks (/sms/webhook, /cms/webhook) have their own signature verification.
  # Production hardening path: Cloud Run IAM + API Gateway for external-facing endpoints.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'hey-seven'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/hey-seven/hey-seven:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=180s'  # SSE_TIMEOUT(60s) + graceful_shutdown(15s) + LLM_pipeline(6_calls*15s) + buffer
      - '--concurrency=50'  # SSE streams hold connections; 50 concurrent per instance with asyncio
      - '--no-traffic'  # Deploy without routing traffic; smoke test validates first
      - '--set-secrets=GOOGLE_API_KEY=google-api-key:latest,API_KEY=hey-seven-api-key:latest,CMS_WEBHOOK_SECRET=cms-webhook-secret:latest,TELNYX_PUBLIC_KEY=telnyx-public-key:latest'
      - '--set-env-vars=ENVIRONMENT=production,LOG_LEVEL=INFO,VERSION=$COMMIT_SHA'
      - '--cpu-boost'  # Full CPU during startup for faster cold start
      - '--min-instances=1'  # Keep one warm instance to avoid cold-start latency
      - '--max-instances=10'  # Cap scaling to prevent DDoS-driven cost runaway
      # Cloud Run HTTP probes (Dockerfile HEALTHCHECK is ignored by Cloud Run).
      # Startup probe: wait for agent + RAG initialization before routing traffic.
      # Liveness probe: detect deadlocked containers (blocked event loop, stuck CB).
      - '--startup-probe-path=/health'
      - '--startup-probe-period=10'
      - '--startup-probe-failure-threshold=6'
      - '--liveness-probe-path=/live'
      - '--liveness-probe-period=30'

  # Step 7: Post-deploy smoke test — validate before routing traffic
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting 30s for container startup..."
        sleep 30
        SERVICE_URL=$(gcloud run services describe hey-seven --region=us-central1 --format='value(status.url)')
        echo "Service URL: $SERVICE_URL"
        # Health check with retries (cold start may take up to 60s)
        for i in 1 2 3; do
          STATUS=$(curl -s -o /tmp/health.json -w '%{http_code}' "$SERVICE_URL/health" --max-time 15)
          echo "Attempt $i: /health returned HTTP $STATUS"
          if [ "$STATUS" = "200" ]; then
            echo "Health response: $(cat /tmp/health.json)"
            # Verify version matches deployed commit
            DEPLOYED_VERSION=$(cat /tmp/health.json | python3 -c "import sys,json; print(json.load(sys.stdin).get('version',''))" 2>/dev/null)
            echo "Deployed version: $DEPLOYED_VERSION, Expected: $COMMIT_SHA"
            if [ -n "$DEPLOYED_VERSION" ] && [ "$DEPLOYED_VERSION" != "$COMMIT_SHA" ]; then
              echo "VERSION MISMATCH: deployed=$DEPLOYED_VERSION expected=$COMMIT_SHA"
              echo "Stale container may be serving old code. Failing smoke test."
              STATUS="version_mismatch"
            fi
            break
          fi
          echo "Retrying in 15s..."
          sleep 15
        done
        if [ "$STATUS" != "200" ]; then
          echo "SMOKE TEST FAILED: /health returned $STATUS after 3 attempts (version_mismatch = stale container)"
          echo "Rolling back to previous revision..."
          PREV=$(cat /workspace/previous-revision.txt)
          if [ "$PREV" != "none" ]; then
            gcloud run services update-traffic hey-seven --region=us-central1 --to-revisions=$PREV=100
            echo "Rolled back to $PREV"
          fi
          exit 1
        fi

  # Step 8: Route 100% traffic to new revision (only after smoke test passes)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'hey-seven'
      - '--region=us-central1'
      - '--to-latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/hey-seven/hey-seven:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
