# Cloud Build CI/CD pipeline for the Casino Host Agent.
#
# Triggered on push to main branch. Builds the Docker image, pushes to
# Artifact Registry, and deploys to Cloud Run with IAM-based auth
# (no --allow-unauthenticated).
#
# Required substitution variables:
#   _REGION: GCP region (default: us-central1)
#   _SERVICE_NAME: Cloud Run service name (default: casino-host-agent)
#   _REPOSITORY: Artifact Registry repository name
#
# Required secrets (set via Secret Manager):
#   GOOGLE_API_KEY: Gemini API key
#   API_KEY: Application-level API key for request auth

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'gcp/Dockerfile'
      - '.'
    id: 'build'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}'
    id: 'push'
    waitFor: ['build']

  # Step 3: Deploy to Cloud Run (IAM auth -- no --allow-unauthenticated)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'APP_VERSION=${SHORT_SHA},USE_FIRESTORE=true,GCP_PROJECT_ID=${PROJECT_ID},ENVIRONMENT=production'
      - '--set-secrets'
      - 'GOOGLE_API_KEY=google-api-key:latest,API_KEY=api-key:latest'
    id: 'deploy'
    waitFor: ['push']

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'casino-host-agent'
  _REPOSITORY: 'hey-seven'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
